# Generated by Django 5.0.1 on 2024-02-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinsevi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudian',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cve_estud', models.BigIntegerField(blank=True, null=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('cve_campus', models.CharField(max_length=3)),
                ('cve_institu', models.CharField(max_length=3)),
                ('cve_program', models.CharField(max_length=3)),
                ('periingr', models.CharField(max_length=9)),
                ('fechingr', models.DateField(blank=True, null=True)),
                ('cve_sexo', models.CharField(max_length=9)),
                ('e_mail', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('aeta', models.BooleanField(default=False)),
                ('consejop', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('niveestu', models.CharField(blank=True, max_length=9, null=True)),
                ('cont_veces', models.IntegerField(default=0)),
                ('cont_final', models.IntegerField(default=0)),
                ('email_ayb', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
