# Generated by Django 5.0.1 on 2024-04-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capcursapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capcurs',
            table='capcurs',
        ),
    ]
