"""
Django settings for SINSCRIP project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
# Configuración para django-sslserver

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8vc@vtv@d6zjx4(qx9t=0l9pwds6280@xogb2dx0vw5l0=0+1v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1:8000', '127.0.0.1']


# Configuración de HTTPS
SECURE_SSL_REDIRECT = False


# Application definition
# Tengo dos aplicaciones
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'capcursapp',
    'crispy_forms',
    'crispy_bootstrap5',
    'sinsevi',
    'sicar',
    'siab',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

APPEND_SLASH = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

X_FRAME_OPTIONS ='SAMEORIGIN'

ROOT_URLCONF = 'SINSCRIP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SINSCRIP.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sinscrip_5',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


#>>> CONFIGURACIONES <<<#
# Periodo de inscripciones
PERIODO = 'PRIMAVERA'
NO_PERIODO = 1 #NUMERO DE PERIODO 1, 2 Ó 3
ANIO = 2024

FECHA_LIMITE = '2024-3-5 17:00:00'
capcurs_on = 1   #Cambiar a 1 para activar
FL_CAPCURS = '2024-3-5 17:00:00' # Fecha limite de captura de cursos

sinsevi_on = 1  #Cambiar a 1 para activar
coordins_on = 1  #Cambiar a 1 para activar
FL_SINSEVI = '2024-3-5 17:00:00' # Fecha limite de inscripciones

siayb_on = 1     #Cambiar a 1 para activar
FL_SIAYB = '2024-3-5 17:00:00'   # Fecha limite de altas y bajas

# FECHA DE NUEVO INGRESO
FN_INGRESO = '2023-09-04'  # Fecha de registro de los estudiantes de nuevo ingreso

# Periodo de AETAS que se van a subir al sistema
PERIODO_AETA = 'O'
ANIO_AETA = 2023

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Backend predeterminado de Django
    'capcursapp.backends.CoordinacionesBackend',  # Backend personalizado para el modelo Coordinaciones
    'sinsevi.backends.EstudianBackend', # Backend personalizado para el modelo Estudian
]


AUTH_USER_MODEL = 'capcursapp.Coordinaciones'


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# Ruta donde se almacenarán los archivos estáticos recopilados para producción

STATIC_URL = '/static/'
STATICFILES_DIRS=(os.path.join(BASE_DIR,'static'),)
# Define la ubicación donde se almacenarán los archivos estáticos recopilados.
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

'''
Para pruebas en produccion con debug = False ejecutar

python manage.py runserver 10.0.0.90:9000 --insecure
'''


